### PR TITLE
Implementing streaming mode

### PR DESCRIPTION
**Pull request by natashenka**
Here's streaming mode.

The set-up is a little bit complicated, because I had to edit one of the webrtc-rs demos, I'd appreciate if you have thoughts on how to make this easier.

### CODE REVIEW

**Comment by wrv** [comment]
This is awesome and works great! I rebased, changed some println's, and added debug outputs. 

What do you think about incorporating the webrtc demo into H26Forge? Is it also possible to view the RTP stream on its own?

**Comment by natashenka** [comment]
Great!

I thought about adding the demo, but I couldn't figure out how to do it without adding the whole webrtc-rs tree to H26forge. But this is my first time using Rust, so maybe you know some trick to add it as a package?

It's not possible to view the RTP stream right now, but one possibility is to add an option to output an RTP dump during stream mode. Then, the stream could be viewed with RTPtools (https://github.com/irtlab/rtptools) afterwards. What do you think?

**Comment by wrv** [comment]
I incorporated the example into h26forge, thus removing a few intermediate steps. I was able to get it working with the JS Fiddle, and removed the packet delay.

I think passing in the seed value should be okay for now. I was imagining something like pointing VLC to rtp://localhost:5004 to view the stream.

Let me know if you have any issues with the incorporated example. If not, then I can go ahead and merge this in :)

**Comment by natashenka** [comment]
This looks great! A few more edits.

- Added trim to base64 encoding, as it didn't work with my Linux text editor's default output
- Added the packet delay as a flag, as I started getting decryption failures on Chrome after about 15 mins without it, and once this happens, fuzzing doesn't work at all. This was a fairly difficult problem to diagnose, so I think it's worthwhile making this flag available
- Minor changes to the docs to use WebRTC terminology (also there is no guarantee that the STUN server will be used for every connection, other methodologies might be used depending on network configuration)

**Comment by wrv** [comment]
My bad -- I thought the packet delay was between H26Forge and the rtp-to-webrtc example, not off to the server.

Thanks again for this addition! I'm excited to see what arises!

**Pull request merged**
